server:
  port: 8081
 
spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: userservice
      authentication-database: admin
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://localhost:8761/eureka/
       
logging:
  level:
    org.springframework.security: DEBUG